name: demo-app
services:
  main:
    env_file:
        - .env
    image: demo-main
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
      args:
        TURBO_API: ${TURBO_API}
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_TOKEN: ${TURBO_TOKEN}
    ports:
      - 3000:3000
  sub:
    env_file:
          - .env
    image: demo-sub
    build:
      context: .
      dockerfile: ./apps/sub/Dockerfile
      args:
        TURBO_API: ${TURBO_API}
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_TOKEN: ${TURBO_TOKEN}
    ports:
      - 3001:3001

