name: demo-app
services:
  main:
    image: demo-main
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
      env_file:
        - .env
    ports:
      - 3000:3000
  sub:
    image: demo-sub
    build:
      context: .
      dockerfile: ./apps/sub/Dockerfile
      env_file:
        - .env
    ports:
      - 3001:3001

